// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_ordre_mission.Models;

namespace gestion_ordre_mission.Migrations
{
    [DbContext(typeof(DbContextIndimnite))]
    [Migration("20210625150410_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("gestion_ordre_mission.Models.Cadre", b =>
                {
                    b.Property<int>("IdCadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Idcorps")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCadre");

                    b.HasIndex("Idcorps");

                    b.ToTable("cadres");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Corps", b =>
                {
                    b.Property<int>("Idcorps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcorps");

                    b.ToTable("corp");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Grades", b =>
                {
                    b.Property<int>("Idgrades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdCadre")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idgrades");

                    b.HasIndex("IdCadre");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdreMission", b =>
                {
                    b.Property<int>("idOrdremission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPers")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateArrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDepart")
                        .HasColumnType("datetime2");

                    b.Property<int>("echlon")
                        .HasColumnType("int");

                    b.Property<bool>("etat")
                        .HasColumnType("bit");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("heureArrivee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("heureDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_trajet")
                        .HasColumnType("int");

                    b.Property<string>("matricule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("montant_total")
                        .HasColumnType("real");

                    b.Property<string>("moyenTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombreCheuvaux")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("objetDepart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrdremission");

                    b.HasIndex("IdPers");

                    b.HasIndex("id_trajet");

                    b.ToTable("ordremission");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdrePaiement", b =>
                {
                    b.Property<int>("IdOrderPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("idOrdreVirement")
                        .HasColumnType("int");

                    b.Property<int>("id_mission")
                        .HasColumnType("int");

                    b.Property<int>("ordermissionidOrdremission")
                        .HasColumnType("int");

                    b.Property<double>("tatalKilo")
                        .HasColumnType("float");

                    b.Property<double>("totalDeplacement")
                        .HasColumnType("float");

                    b.HasKey("IdOrderPaiement");

                    b.HasIndex("idOrdreVirement");

                    b.HasIndex("ordermissionidOrdremission");

                    b.ToTable("ordrepaiement");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdrePayment", b =>
                {
                    b.Property<int>("IdOrdrePayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("idOrdreVirement")
                        .HasColumnType("int");

                    b.Property<int?>("idOrdremission")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double>("tatalKilo")
                        .HasColumnType("float");

                    b.Property<double>("totalDeplacement")
                        .HasColumnType("float");

                    b.HasKey("IdOrdrePayment");

                    b.HasIndex("idOrdreVirement");

                    b.HasIndex("idOrdremission");

                    b.ToTable("OrdrePayment");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdreVirement", b =>
                {
                    b.Property<int>("IdOrdreVirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdOrderPaiement")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdOrdrePayment")
                        .HasColumnType("int");

                    b.Property<int>("idAdmin")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroCompte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrdreVirement");

                    b.HasIndex("IdOrderPaiement");

                    b.HasIndex("IdOrdrePayment");

                    b.ToTable("ordrevirement");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Parameter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valeur1")
                        .HasColumnType("int");

                    b.Property<int>("valeur2")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("parametre");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Parametre_image", b =>
                {
                    b.Property<int>("id_param_img")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("footer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_param_img");

                    b.ToTable("parametre_img");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Parametre_paiement", b =>
                {
                    b.Property<int>("id_param_paiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<int>("num1")
                        .HasColumnType("int");

                    b.Property<int>("num2")
                        .HasColumnType("int");

                    b.HasKey("id_param_paiement");

                    b.ToTable("param_paiement");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Parametre_voiture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("nombre_cheveau_max")
                        .HasColumnType("int");

                    b.Property<int>("nombre_cheveau_min")
                        .HasColumnType("int");

                    b.Property<float>("prix_par_km")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("param_voiture");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Personnel", b =>
                {
                    b.Property<int>("IdPers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateContract")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffetEchelon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffetgrade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecrutement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecrutementENSA")
                        .HasColumnType("datetime2");

                    b.Property<int>("Echelle")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsm1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsm2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCadre")
                        .HasColumnType("int");

                    b.Property<int?>("Idcorps")
                        .HasColumnType("int");

                    b.Property<int?>("Idgrades")
                        .HasColumnType("int");

                    b.Property<string>("Journauxrecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieuentiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCorps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomGrades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreEnfant")
                        .HasColumnType("int");

                    b.Property<string>("Nomentiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAffecte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationAdministratif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationFamiliale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Société")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thematiquerecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typecontract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeqEntiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("anneediplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("echelon")
                        .HasColumnType("int");

                    b.Property<string>("ecolediplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("liencv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("renouvelement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("show1")
                        .HasColumnType("bit");

                    b.Property<bool>("show2")
                        .HasColumnType("bit");

                    b.Property<string>("specialite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPers");

                    b.HasIndex("IdCadre");

                    b.HasIndex("Idcorps");

                    b.HasIndex("Idgrades");

                    b.ToTable("personnels");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Trajet", b =>
                {
                    b.Property<int>("id_trajet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("distance")
                        .HasColumnType("int");

                    b.Property<string>("villeArrivee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("villeDepart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_trajet");

                    b.ToTable("trajet");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Cadre", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.Corps", "corps")
                        .WithMany("caders")
                        .HasForeignKey("Idcorps");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Grades", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.Cadre", "Cadre")
                        .WithMany("Grades")
                        .HasForeignKey("IdCadre");
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdreMission", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.Personnel", "personel")
                        .WithMany("ordermissions")
                        .HasForeignKey("IdPers")
                   
                        .IsRequired();

                    b.HasOne("gestion_ordre_mission.Models.Trajet", "trajet")
                        .WithMany("OrdreMissions")
                        .HasForeignKey("id_trajet")
                        
                        .IsRequired();
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdrePaiement", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.OrdreVirement", "ordreVirement")
                        .WithMany()
                        .HasForeignKey("idOrdreVirement");

                    b.HasOne("gestion_ordre_mission.Models.OrdreMission", "ordermission")
                        .WithMany("ordrePaiement")
                        .HasForeignKey("ordermissionidOrdremission")
                        
                        .IsRequired();
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdrePayment", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.OrdreVirement", "ordreVirement")
                        .WithMany()
                        .HasForeignKey("idOrdreVirement");

                    b.HasOne("gestion_ordre_mission.Models.OrdreMission", "ordermission")
                        .WithMany("ordrePayment")
                        .HasForeignKey("idOrdremission")
                        .IsRequired();
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.OrdreVirement", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.OrdrePaiement", "orderpaiment")
                        .WithMany()
                        .HasForeignKey("IdOrderPaiement")
                        .IsRequired();

                    b.HasOne("gestion_ordre_mission.Models.OrdrePayment", "orderPayment")
                        .WithMany()
                        .HasForeignKey("IdOrdrePayment")
                        
                        .IsRequired();
                });

            modelBuilder.Entity("gestion_ordre_mission.Models.Personnel", b =>
                {
                    b.HasOne("gestion_ordre_mission.Models.Cadre", "Cadre")
                        .WithMany("Personnels")
                        .HasForeignKey("IdCadre");

                    b.HasOne("gestion_ordre_mission.Models.Corps", "Corps")
                        .WithMany("Personnels")
                        .HasForeignKey("Idcorps");

                    b.HasOne("gestion_ordre_mission.Models.Grades", "Grades")
                        .WithMany("Personnels")
                        .HasForeignKey("Idgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
